version: '3'
services:
  categoria:
    image: categoria
    ports:
      - "9092:9092"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - CATEGORIA_PORT=9092
      - ECOMMERCE_DB_NAME=ecommerce
      - MYSQL_IP=localhost
      - MYSQL_PORT=3306
      - PASS=password
      - USER=root
    networks:
      - my-network
  cliente:
    image: cliente
    ports:
      - "9093:9093"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - CLIENTE_PORT=9093
      - ECOMMERCE_DB_NAME=ecommerce
      - MYSQL_IP=localhost
      - MYSQL_PORT=3306
      - PASS=password
      - USER=root
    networks:
      - my-network
  products:
    image: products
    ports:
      - "9091:9091"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - PRODUCTS_PORT=9091
      - ECOMMERCE_DB_NAME=ecommerce
      - MYSQL_IP=localhost
      - MYSQL_PORT=3306
      - PASS=password
      - USER=root
    networks:
      - my-network
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=ecommerce
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
